name: Build APK for release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'keystore.jks'
          encodedString: ${{ secrets.KEYSTORE }}
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: build prod
        run: ./gradlew assembleRelease
        env:
          SIGNING_STORE_FILE: ${{ steps.decode_keystore.outputs.filePath }}
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
      - name: Rename APK
        run: cp app/build/outputs/apk/release/app-release.apk somnia-${{ github.ref_name }}.apk 
      - name: Upload release Asset
        env:
          GH_TOKEN: ${{ github.token }}
        run:
          gh release upload ${{ github.ref_name }} somnia-${{ github.ref_name }}.apk
